;;;; logfmt-logger.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'logfmt-logger
      'logfmt-logger
      (scheme#list)
      '((log-debug . logfmt-logger#log-debug)
        (log-info . logfmt-logger#log-info)
        (log-warning . logfmt-logger#log-warning)
        (log-error . logfmt-logger#log-error)
        (log-level . logfmt-logger#log-level)
        (log-port . logfmt-logger#log-port))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
